// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package confort

import (
	"context"
	"github.com/docker/docker/api/types"
	"github.com/docker/go-connections/nat"
	"io"
	"sync"
)

// Ensure, that FetcherMock does implement Fetcher.
// If this is not the case, regenerate this file with moq.
var _ Fetcher = &FetcherMock{}

// FetcherMock is a mock implementation of Fetcher.
//
// 	func TestSomethingThatUsesFetcher(t *testing.T) {
//
// 		// make and configure a mocked Fetcher
// 		mockedFetcher := &FetcherMock{
// 			EndpointsFunc: func() map[nat.Port]string {
// 				panic("mock out the Endpoints method")
// 			},
// 			LogFunc: func(ctx context.Context) (io.ReadCloser, error) {
// 				panic("mock out the Log method")
// 			},
// 			StatusFunc: func(ctx context.Context) (*types.ContainerState, error) {
// 				panic("mock out the Status method")
// 			},
// 		}
//
// 		// use mockedFetcher in code that requires Fetcher
// 		// and then make assertions.
//
// 	}
type FetcherMock struct {
	// EndpointsFunc mocks the Endpoints method.
	EndpointsFunc func() map[nat.Port]string

	// LogFunc mocks the Log method.
	LogFunc func(ctx context.Context) (io.ReadCloser, error)

	// StatusFunc mocks the Status method.
	StatusFunc func(ctx context.Context) (*types.ContainerState, error)

	// calls tracks calls to the methods.
	calls struct {
		// Endpoints holds details about calls to the Endpoints method.
		Endpoints []struct {
		}
		// Log holds details about calls to the Log method.
		Log []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Status holds details about calls to the Status method.
		Status []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockEndpoints sync.RWMutex
	lockLog       sync.RWMutex
	lockStatus    sync.RWMutex
}

// Endpoints calls EndpointsFunc.
func (mock *FetcherMock) Endpoints() map[nat.Port]string {
	if mock.EndpointsFunc == nil {
		panic("FetcherMock.EndpointsFunc: method is nil but Fetcher.Endpoints was just called")
	}
	callInfo := struct {
	}{}
	mock.lockEndpoints.Lock()
	mock.calls.Endpoints = append(mock.calls.Endpoints, callInfo)
	mock.lockEndpoints.Unlock()
	return mock.EndpointsFunc()
}

// EndpointsCalls gets all the calls that were made to Endpoints.
// Check the length with:
//     len(mockedFetcher.EndpointsCalls())
func (mock *FetcherMock) EndpointsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockEndpoints.RLock()
	calls = mock.calls.Endpoints
	mock.lockEndpoints.RUnlock()
	return calls
}

// Log calls LogFunc.
func (mock *FetcherMock) Log(ctx context.Context) (io.ReadCloser, error) {
	if mock.LogFunc == nil {
		panic("FetcherMock.LogFunc: method is nil but Fetcher.Log was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockLog.Lock()
	mock.calls.Log = append(mock.calls.Log, callInfo)
	mock.lockLog.Unlock()
	return mock.LogFunc(ctx)
}

// LogCalls gets all the calls that were made to Log.
// Check the length with:
//     len(mockedFetcher.LogCalls())
func (mock *FetcherMock) LogCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockLog.RLock()
	calls = mock.calls.Log
	mock.lockLog.RUnlock()
	return calls
}

// Status calls StatusFunc.
func (mock *FetcherMock) Status(ctx context.Context) (*types.ContainerState, error) {
	if mock.StatusFunc == nil {
		panic("FetcherMock.StatusFunc: method is nil but Fetcher.Status was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStatus.Lock()
	mock.calls.Status = append(mock.calls.Status, callInfo)
	mock.lockStatus.Unlock()
	return mock.StatusFunc(ctx)
}

// StatusCalls gets all the calls that were made to Status.
// Check the length with:
//     len(mockedFetcher.StatusCalls())
func (mock *FetcherMock) StatusCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStatus.RLock()
	calls = mock.calls.Status
	mock.lockStatus.RUnlock()
	return calls
}
