// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package database

import ()

type Employee struct {
	ID       int32  `db:"id"`
	Name     string `db:"name"`
	TenantID int32  `db:"tenant_id"`
}

type Tenant struct {
	ID   int32  `db:"id"`
	Name string `db:"name"`
}
