// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: unique.proto

package beacon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreUniqueValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store string `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StoreUniqueValueRequest) Reset() {
	*x = StoreUniqueValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreUniqueValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreUniqueValueRequest) ProtoMessage() {}

func (x *StoreUniqueValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreUniqueValueRequest.ProtoReflect.Descriptor instead.
func (*StoreUniqueValueRequest) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{0}
}

func (x *StoreUniqueValueRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *StoreUniqueValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StoreUniqueValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeeded bool `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
}

func (x *StoreUniqueValueResponse) Reset() {
	*x = StoreUniqueValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unique_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreUniqueValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreUniqueValueResponse) ProtoMessage() {}

func (x *StoreUniqueValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unique_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreUniqueValueResponse.ProtoReflect.Descriptor instead.
func (*StoreUniqueValueResponse) Descriptor() ([]byte, []int) {
	return file_unique_proto_rawDescGZIP(), []int{1}
}

func (x *StoreUniqueValueResponse) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

var File_unique_proto protoreflect.FileDescriptor

var file_unique_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x22, 0x45, 0x0a, 0x17, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x38, 0x0a,
	0x18, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x32, 0x6b, 0x0a, 0x12, 0x55, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a,
	0x10, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1f, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x65,
	0x61, 0x63, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unique_proto_rawDescOnce sync.Once
	file_unique_proto_rawDescData = file_unique_proto_rawDesc
)

func file_unique_proto_rawDescGZIP() []byte {
	file_unique_proto_rawDescOnce.Do(func() {
		file_unique_proto_rawDescData = protoimpl.X.CompressGZIP(file_unique_proto_rawDescData)
	})
	return file_unique_proto_rawDescData
}

var file_unique_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_unique_proto_goTypes = []interface{}{
	(*StoreUniqueValueRequest)(nil),  // 0: beacon.StoreUniqueValueRequest
	(*StoreUniqueValueResponse)(nil), // 1: beacon.StoreUniqueValueResponse
}
var file_unique_proto_depIdxs = []int32{
	0, // 0: beacon.UniqueValueService.StoreUniqueValue:input_type -> beacon.StoreUniqueValueRequest
	1, // 1: beacon.UniqueValueService.StoreUniqueValue:output_type -> beacon.StoreUniqueValueResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_unique_proto_init() }
func file_unique_proto_init() {
	if File_unique_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unique_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreUniqueValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unique_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreUniqueValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unique_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unique_proto_goTypes,
		DependencyIndexes: file_unique_proto_depIdxs,
		MessageInfos:      file_unique_proto_msgTypes,
	}.Build()
	File_unique_proto = out.File
	file_unique_proto_rawDesc = nil
	file_unique_proto_goTypes = nil
	file_unique_proto_depIdxs = nil
}
