name: unit test
on:
  push:
    paths:
      - "**.go"
      - ".github/workflows/test.yml"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: test
        run: make test-cov-ci
      - name: setup Pages
        uses: actions/configure-pages@v1
        if: github.ref == 'refs/heads/actions'
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './.cov'
        if: github.ref == 'refs/heads/actions'
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
        if: github.ref == 'refs/heads/actions'
