name: unit test
on:
  push:
    paths:
      - "**.go"
      - ".github/workflows/test.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: test
        run: make test-cov-ci
      - name: push
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.cov
        if: github.ref == 'refs/heads/actions'
